# Builds the mod on each release

name: build
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: add artifacts to release
        run: gh release upload ${GITHUB_REF#refs/*/} build/libs/kassette-*.jar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash